export const UNAUTHORIZED_WRONG_CREDENTIALS = 'UNAUTHORIZED_WRONG_CREDENTIALS';

export const UNAUTHORIZED_TOKEN_EXPIRED = 'UNAUTHORIZED_TOKEN_EXPIRED';

export const UNAUTHORIZED_USER_NOTFOUND = 'UNAUTHORIZED_USER_NOTFOUND';

export const UNAUTHORIZED_USER_EXIST = 'UNAUTHORIZED_USER_EXIST';
