export enum ErrorCode {
    UNAUTHORIZED_WRONG_CREDENTIALS = 'UNAUTHORIZED_WRONG_CREDENTIALS',
    UNAUTHORIZED_TOKEN_EXPIRED = 'UNAUTHORIZED_TOKEN_EXPIRED',
    UNAUTHORIZED_REFRESH_TOKEN_EXPIRED = 'UNAUTHORIZED_REFRESH_TOKEN_EXPIRED',
    UNAUTHORIZED_USER_NOTFOUND = 'UNAUTHORIZED_USER_NOTFOUND',
    UNAUTHORIZED_USER_EXIST = 'UNAUTHORIZED_USER_EXIST',
    UNAUTHORIZED_AUTH_FAILED = 'UNAUTHORIZED_AUTH_FAILED',
    UNIQUE_ERROR = 'UNIQUE_ERROR',
}
